### ISSUE TITLE
关于脚本的一个小问题

### ISSUE THREAD

**Issue by zzh-editor** [weirick/AllSiteDefaultFont#1]
1.整体的显示效果很棒，但在登录一些网站时无法显示输入框，如京东：
![image](https://user-images.githubusercontent.com/39148825/77871088-a4cf2380-7275-11ea-8f9b-926395a15d86.png)

**Comment by zzh-editor** [comment]
补充一点：访问「吾爱破解」时，无法调出板块内的复选框，如：
![image](https://user-images.githubusercontent.com/39148825/77871253-2626b600-7276-11ea-9fbb-620f01b8ccd4.png)

**Comment by sakowei** [comment]
其实这个问题我自己也遇到过，准备修改

**Comment by sakowei** [comment]
现在修改好了，试着更新一下脚本，不过这个脚本其实还是没有完全做到去掉加粗 @iszhjane

**Comment by zzh-editor** [comment]
太棒了
